version: '3'
services:
  my-service:
    container_name: inventory-service
    image: prod-ser
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/app/logs
      - ./config:/app/config